name: Windows RDP via Tailscale (portable)

on:
  workflow_dispatch:

jobs:
  rdp:
    runs-on: windows-latest
    env:
      RDP_USER: Afdy22
      RDP_PASS: SquadLA22
      TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
    steps:
      - name: Download Tailscale portable
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-ipn-setup-latest.exe" -OutFile tailscale.exe

      - name: Start tailscaled in userspace
        shell: pwsh
        run: |
          Start-Process -FilePath .\tailscale.exe -ArgumentList "serve" -WindowStyle Hidden
          Start-Sleep -Seconds 5

      - name: Tailscale up
        shell: pwsh
        run: |
          .\tailscale.exe up --authkey $env:TAILSCALE_AUTHKEY --hostname github-runner --accept-routes --accept-dns

      - name: Get Tailscale IP
        shell: pwsh
        run: |
          .\tailscale.exe ip -4

      - name: Enable RDP
        shell: pwsh
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name 'fDenyTSConnections' -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop" -ErrorAction SilentlyContinue
          net user $env:RDP_USER $env:RDP_PASS /add
          net localgroup administrators $env:RDP_USER /add

      - name: Show connection info
        shell: pwsh
        run: |
          $ip = .\tailscale.exe ip -4
          Write-Host "Connect RDP ke: $ip"
          Write-Host "User: $env:RDP_USER"
          Write-Host "Pass: $env:RDP_PASS"

      - name: Keep alive
        shell: pwsh
        run: Start-Sleep -Seconds 900
